### PR TITLE
Remove migrations from .gitignore

### LINKED ISSUE #7: Remove migrations from .gitignore

### PR DESCRIPTION
**Pull request by Aviral14**
Closes #7

### CODE REVIEW

**Comment by Aviral14** [comment]
Formatting Updated!

**Comment by iamkroot** [comment]
Let's get #6 merged first. Then we'll handle this one.

**Comment by iamkroot** [comment]
Now onto this PR @Aviral14

**Comment by iamkroot** [comment]
You'll have to resolve the merge conflicts first.

**Comment by Aviral14** [comment]
@iamkroot Please review.

**Comment by iamkroot** [comment]
Change PR Title/Body, and squash all the commits.

**Pull request merged**
